[[task]]
name = "ls"
cmd = "ls -l ~"
autostart = false
numprocess = 1
umask = 777
workingdir = "/tmp"
stdout = "/tmp/ls.out"
stopsignal = "TERM"
stderr = "/tmp/ls.err"

[[task]]
name = "ls homer"
cmd = "ls -l /Users/cempassi/Programming"
autostart = false
numprocess = 1
umask = 777
workingdir = "/tmp"
stopsignal = "TERM"
stdout = "/tmp/ls_home.out"
stderr = "/tmp/ls_home.err"
